apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-config
  template:
    metadata:
      labels:
        app: nginx-config
    spec:
      containers:
      - name: nginx
        image: nginx
        env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_NAME
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: PASSWORD
